//
// Generated file, do not edit! Created by opp_msgc 4.3 from linklayer/mfcore/SnrControlInfo.msg.
//

#ifndef _SNRCONTROLINFO_M_H_
#define _SNRCONTROLINFO_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "INETDefs.h"
#include "SnrList.h"
// }}



/**
 * Class generated from <tt>linklayer/mfcore/SnrControlInfo.msg</tt> by opp_msgc.
 * <pre>
 * class SnrControlInfo
 * {
 *     SnrList snrList;
 * }
 * </pre>
 */
class SnrControlInfo : public ::cObject
{
  protected:
    SnrList snrList_var;

  private:
    void copy(const SnrControlInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SnrControlInfo&);

  public:
    SnrControlInfo();
    SnrControlInfo(const SnrControlInfo& other);
    virtual ~SnrControlInfo();
    SnrControlInfo& operator=(const SnrControlInfo& other);
    virtual SnrControlInfo *dup() const {return new SnrControlInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual SnrList& getSnrList();
    virtual const SnrList& getSnrList() const {return const_cast<SnrControlInfo*>(this)->getSnrList();}
    virtual void setSnrList(const SnrList& snrList);
};

inline void doPacking(cCommBuffer *b, SnrControlInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SnrControlInfo& obj) {obj.parsimUnpack(b);}


#endif // _SNRCONTROLINFO_M_H_
